project-b-13-main/Housing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('app/', include('app.urls')),
    path('dwjidjqwodjqwiodjqoi/78qwe78w7e8qw/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project-b-13-main/app/urls.py
from django.urls import path, include
from .import views
from django.contrib.auth.views import LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'app'
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # Filter paths
    path('filter/', views.FilterView, name='filter'),
    path('filter/<str:name>', views.PropertyView, name='property'),

    # Map paths
    path('map/', views.MapView.as_view(), name='map'),

    # About
    path('about/', views.AboutView.as_view(), name='about'),

    # Search
    path('search_housing/', views.search_housing, name='search_housing')
]

project-b-13-main/app/templates/app/about.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load static %}
{% load socialaccount %}
<html>
    <head>
        <title>UVA Off-Grounds Housing</title>
    </head>
<body>
<!-- <h1>My Google OAuth Project </h1> -->

<nav class="navbar navbar-expand navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/app" style="color:#FF8C00">UVA Off-Grounds Housing</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/app">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:filter' %}">Filter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:map' %}">Map</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:about' %}">About</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
            <li class="nav-link" style="float: right;">User: {{ user.username }}</li>
            <a href="{% url 'app:logout' %}">{% load static %}<img src="{% static 'media/google-logout.png' %}" alt="home" height="50"></a>
        {% else %}
            <a href="{% provider_login_url 'google' %}">
            <img 
                src="https://onymos.com/wp-content/uploads/2020/10/google-signin-button-1024x260.png" 
                height="50"
            >
            </a>
        {% endif %}
        </div>
    </div>
</nav>

<h1 style="color: rgb(8, 11, 133); padding-left: 0.1in;">About This Project</h1>
<div class="col-sm-12" style="padding-left: 1%; padding-right: 1%;">
    <div class="card">
        <div class="card-body">
        <h5 class="card-title">CS 3240 - Fall 2021</h5>
        <p class="card-text">The application is created by 5 undergraduate students for CS 3240: 
            Advanced Software Development Techniques in fall 2021 at the University of Virginia. 
            It allowers users to search, filter, find, and leave comments/ratings about off-grounds 
            housing for the university. This is a semester long project and the software uses Django, 
            Python, Bootstrap, Heroku, and other API services.

            If you want to learn
            more about us, please refer to our personal links below.
        </p>
        <a href="http://cs3240.cs.virginia.edu/" class="card-link">
            About this course</a>
        </div>
    </div>
</div>

<h1 style="color: rgb(8, 11, 133); padding-left: 0.1in;padding-top: 0.1in;">Team</h1>
<div class="container-fluid">
    <div class="row">
    <div class="col-sm-2">
        <div class="card" style="width: 14rem; height: 15rem;">
            <div class="card-body">
            <h5 class="card-title">Chloe Smith</h5>
            <h6 class="card-subtitle mb-2 text-muted">Scrum Master</h6>
            <a href="https://github.com/chloeSmitth" class="card-link">GitHub</a>
            <a href="https://www.linkedin.com/in/chloe-smith-733b05221/" class="card-link">LinkedIn</a>
            <p class="card-text">
                Hello, I am interested in software development, UX design, cybersecurtity, Machine Learning, etc.
            </p>
            </div>
        </div>
    </div>
    <div class="col-sm-2">
        <div class="card" style="width: 14rem; height: 15rem;right: -45;">
            <div class="card-body">
            <h5 class="card-title">Vinny Peng</h5>
            <h6 class="card-subtitle mb-2 text-muted">UX Designer</h6>
            <a href="https://github.com/vinnypeng2000" class="card-link">GitHub</a>
            <a href="https://www.linkedin.com/in/vinnypeng1116/" class="card-link">LinkedIn</a>
            <p class="card-text">Hello, I am interested in software development, game
                development, AI, HCI, etc.</p>
            </div>
        </div>
    </div>
    <div class="col-sm-2">
        <div class="card" style="width: 14rem; height: 15rem;right: -90;">
            <div class="card-body">
            <h5 class="card-title">Katie Shewell</h5>
            <h6 class="card-subtitle mb-2 text-muted">Requirements Manager</h6>
            <a href="https://github.com/katieshewell">GitHub</a>
            <a href="https://www.linkedin.com/in/katherine-shewell-0497721b5/" class="card-link">LinkedIn</a>
            <p class="card-text">
                Hello, I am interested in data science and UX design!</p>
            </div>
        </div>
    </div>
    <div class="col-sm-2">
        <div class="card" style="width: 14rem; height: 15rem; right: -135;">
            <div class="card-body">
            <h5 class="card-title">King Shing Chau</h5>
            <h6 class="card-subtitle mb-2 text-muted">DevOps Manager</h6>
            <a href="#" class="card-link">GitHub</a>
            <a href="#" class="card-link">LinkedIn</a>
            <p class="card-text">
                Hello, I am interested in game desing, game development, cybersecurity etc.</p>
            </div>
        </div>
    </div>
    <div class="col-sm-2">
        <div class="card" style="width: 14rem; height: 15rem; right: -180;">
            <div class="card-body">
            <h5 class="card-title">Shiva Manandhar</h5>
            <h6 class="card-subtitle mb-2 text-muted">Testing Manager</h6>
            <a href="#" class="card-link">GitHub</a>
            <a href="#" class="card-link">LinkedIn</a>
            <p class="card-text">
                Hello, I am interested in software development, Machine Learning/AI, Hardware Design, etc.</p>
            </div>
        </div>
    </div>
    </div>
    </div>
    <br/>
    <br/>

<div style="position: fixed; bottom: 0%; width: 100%;">
    <footer class="text-center bg-light">
        <div class="text-center p-2" style="font-size: 14; background-color: rgba(0, 0, 0, 0.05);">
        © 2021 Copyright: Students in project b-13 in CS 3240: Advanced Software Development Techniques. 
        University of Virginia.
        </div>
    </footer>
</div>

</body>
</html>

project-b-13-main/app/templates/app/filter.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load static %}
{% load socialaccount %}

<html>
    <head>
        <title>UVA Off-Grounds Housing</title>
    </head>

<body>

<nav class="navbar navbar-expand navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/app" style="color:#FF8C00">UVA Off-Grounds Housing</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/app">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:filter' %}">Filter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:map' %}">Map</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:about' %}">About</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
            <li class="nav-link" style="float: right;">User: {{ user.username }}</li>
            <a href="{% url 'app:logout' %}">{% load static %}
                <img src="{% static 'media/google-logout.png' %}" alt="home" height="50"></a>
        {% else %}
            <a href="{% provider_login_url 'google' %}">
            <img 
                src="https://onymos.com/wp-content/uploads/2020/10/google-signin-button-1024x260.png" 
                height="50"
            >
            </a>
        {% endif %}
        </div>
    </div>
</nav>

<br>

<br>
<div class="row" style="position:relative; top: -40px; padding-left: 0.5in; padding-right: 0.5in;">
	<div class="col">
		<center><div class="card card-body">
            
			<form method="get" style="font-size: 15;">
                {{otherFilter.form}}
				{{style_filter.form}}
		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>

		</div></center>
	</div>
	
</div>

<div class="row" style="position:relative; top: -30; padding-left: 0.5in; padding-right: 0.5in;">
	<div class="col-md">
		<div class="card card-body">
			<table class="table table-sm">
             
				{% for x in housings %}
                    {% for y in style_qs %}
                        {% if y.name.name == x.name %}
				<tr>
                    <div class="card mb-4">
                        <div class="row no-gutters">
                            <div class="col-md-4">
                                <img src="{{ x.image.url }}" style="height: 220px; 
                                width: 100%; padding: 10px;" />
                            </div>
                            <div class="col-md-5">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <a href="{% url 'app:property' x.name %}" 
                                        style="color: rgb(8, 11, 133);">{{x.name}}</a></h5>
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item">
                                            Building Type: {{x.housing_type}}
                                        </li>
                                        <li class="list-group-item">Address: {{x.address}}</li>
                                        <li class="list-group-item">
                                            Monthly Rent($): {{y.rent}}
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-3" style="padding-top: 32px;">
                                <div class="card-body">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item">People: 
                                            {{y.people}}</li>
                                        <li class="list-group-item">Bedrooms: 
                                            {{y.beds}}</li>
                                        <li class="list-group-item">Bathrooms: 
                                            {{y.baths}}</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
				</tr>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
			</table>
		</div>
	</div>
</div>

<div style="position: relative; bottom: 0%; width: 100%;">
    <footer class="text-center bg-light">
      <div class="text-center p-2" style="font-size: 14; background-color: rgba(0, 0, 0, 0.05);">
        © 2021 Copyright: Students in project b-13 in CS 3240: Advanced Software Development Techniques. 
        University of Virginia.
      </div>
    </footer>
</div>

</body>
</html>

project-b-13-main/app/templates/app/index.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load static %}
{% load socialaccount %}
<html>
  <head>
    <title>UVA Off-Grounds Housing</title>
  </head>

<body>

<!-- <div class='tiledBackground'> -->
  <link rel="stylesheet" type="text/css" href="{% static 'background.css' %}" style="width:fit-content;">
<!-- </div> -->

<nav class="navbar navbar-expand navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/app" style="color:#FF8C00">UVA Off-Grounds Housing</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/app">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:filter' %}">Filter</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:map' %}">Map</a>
        </li>       
        <li class="nav-item">
        <a class="nav-link" href="{% url 'app:about' %}">About</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
        <li class="nav-link" style="float: right;">User: {{ user.username }}</li>
        <a href="{% url 'app:logout' %}">{% load static %}<img src="{% static 'media/google-logout.png' %}" alt="home" height="50"></a>
      {% else %}
        <a href="{% provider_login_url 'google' %}">
          <img 
            src="https://onymos.com/wp-content/uploads/2020/10/google-signin-button-1024x260.png" 
            height="50"
          >
        </a>
      {% endif %}
    </div>
  </div>
</nav>{

<div style="position:relative; 
  top: 0px; padding-left: 70px;margin: 150px; padding-right: 70px; padding-top: 20px;">
  <div style = "opacity: .7;">
  <form class="navbar-form navbar-left mt-3" method=POST action="{% url 'app:search_housing' %}">
  {% csrf_token %}
  <input 
    class="form-control me-2" 
    type="search" 
    placeholder="Search Housing..." 
    aria-label="Search" 
    name="searching" />
  </div>
  <div style="padding: 6ch;">
    <center><button class="btn btn-warning" type="submit">Search</button></center>
    
  </div>
</form>
</div>


<div style="position: fixed; bottom: 0%; width: 100%;">
  <footer class="text-center bg-light">
    <div class="text-center p-2" style="font-size: 14; background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright: Students in project b-13 in CS 3240: Advanced Software Development Techniques. 
      University of Virginia.
    </div>
  </footer>
</div>

</body>
</html>

project-b-13-main/app/templates/app/indexnosearch.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
{% load socialaccount %}
<html>
  <head>
    <title>UVA Off-Grounds Housing</title>
  </head>

<body>

<!-- <div class='tiledBackground'> -->
  <link rel="stylesheet" type="text/css" href="{% static 'background.css' %}" style="width:fit-content;">
<!-- </div> -->

<nav class="navbar navbar-expand navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/app" style="color:#FF8C00">UVA Off-Grounds Housing</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/app">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:filter' %}">Filter</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app:map' %}">Map</a>
        </li>       
        <li class="nav-item">
        <a class="nav-link" href="{% url 'app:about' %}">About</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
        <li class="nav-link" style="float: right;">User: {{ user.username }}</li>
        <a href="{% url 'app:logout' %}">{% load static %}<img src="{% static 'media/google-logout.png' %}" alt="home" height="50"></a>
      {% else %}
        <a href="{% provider_login_url 'google' %}">
          <img 
            src="https://onymos.com/wp-content/uploads/2020/10/google-signin-button-1024x260.png" 
            height="50"
          >
        </a>
      {% endif %}
    </div>
  </div>
</nav>{

<div style="position:relative; 
  top: 0px; padding-left: 70px;margin: 150px; padding-right: 70px; padding-top: 20px;">
  <div style = "opacity: .7;">
  <form class="navbar-form navbar-left mt-3" method=POST action="{% url 'app:search_housing' %}">
  {% csrf_token %}
  <input 
    class="form-control me-2" 
    type="search" 
    placeholder="Search Housing..." 
    aria-label="Search" 
    name="searching" />
  </div>
  <div style="padding: 6ch;">
    <div class="alert alert-success" role="alert">
      you did not type anything; try again
    </div>
    <center><button class="btn btn-warning" type="submit">Search</button></center>
    
  </div>
</form>
</div>


<div style="position: fixed; bottom: 0%; width: 100%;">
  <footer class="text-center bg-light">
    <div class="text-center p-2" style="font-size: 14; background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright: Students in project b-13 in CS 3240: Advanced Software Development Techniques. 
      University of Virginia.
    </div>
  </footer>
</div>

</body>
</html>

project-b-13-main/app/templates/app/property.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load static %}
{% load socialaccount %}

<html>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-6191f87f8ee10034"></script>
<head>
        <script src='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js'></script>
        <link href='https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css' rel='stylesheet' />
    <title>UVA Off-Grounds Housing</title>
</head>   
<body>

<nav class="navbar navbar-expand navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/app" style="color:#FF8C00">UVA Off-Grounds Housing</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/app">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:filter' %}">Filter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:map' %}">Map</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:about' %}">About</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
            <li class="nav-link" style="float: right;">User: {{ user.username }}</li>
            <a href="{% url 'app:logout' %}">{% load static %}<img src="{% static 'media/google-logout.png' %}" alt="home" height="50"></a>
        {% else %}
            <a href="{% provider_login_url 'google' %}">
            <img 
                src="https://onymos.com/wp-content/uploads/2020/10/google-signin-button-1024x260.png" 
                height="50"
            >
            </a>
        {% endif %}
        </div>
    </div>
</nav>

<center><h1 style="color: rgb(8, 11, 133);">{{property.name}}</h1></center>

<div class="container">
<div class="row">
<div id="carouselExampleIndicators" class="carousel slide col-md-6" 
  data-bs-ride="carousel" >
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{ pics.pic1.url }}" class="d-block w-100" style="height: 400; width: 300;">
    </div>
    <div class="carousel-item">
      <img src="{{ pics.pic2.url }}" class="d-block w-100" style="height: 400; width: 300;">
    </div>
    <div class="carousel-item">
      <img src="{{ pics.pic3.url }}" class="d-block w-100" style="height: 400; width: 300;">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

<div class="col-md-6">
  <div id='map' style='width: 100%; height: 100%;'></div>
</div>

</div></div>

<div class="col-md-12" style="padding-top: 0.1in; padding-left: 0.6in; padding-right: 0.6in;">
  <ul class="list-group">
    {% if property.housing_type == 'Town_House' %}
    <li class="list-group-item"><b>Type:</b> Town House</li>
    {% endif %}
    {% if property.housing_type != 'Town_House' %}
    <li class="list-group-item"><b>Type:</b> {{property.housing_type}}</li>
    {% endif %}
    <li class="list-group-item"><b>Address:</b> {{property.address}}</li>
    {% for i in amenities %}
    <li class="list-group-item"><b>Amenities:</b> {{i.amenities}}</li>
    <li class="list-group-item"><b>Utilities:</b> {{i.utilities}}</li>
    {% endfor %}
  </ul>
</div>

<br/>
<center><h4 style="color: rgb(8, 11, 133);">All Floor Plans in This Property</h4></center>

<div style="padding-left: 0.6in; padding-right: 0.6in;">
<table class='table'>
    <tr>
    <th scope='col' width='25%'>People</th>
    <th scope='col' width='25%'>Bedrooms</th>
    <th scope='col' width='25%'>Bathrooms</th>
    <th scope='col' width='25%'>Monthly Rent ($)</th>
  </tr>
  {% for i in detail %}
  <tr>
    <td>{{i.people}}</td>
    <td>{{i.beds}}</td>
    <td>{{i.baths}}</td>
    <td>{{i.rent}}</td>
  </tr>
  {% endfor %}
</table>
</div>

    <div class="container">
        <div class="row">
          <div class="col-md-12 card mb-4  mt-3 left  top">
            <div class="card-body">
              <h4 style="color: rgb(8, 11, 133);">Student Reviews for {{property.name}}</h4>
              <br>
              {% if avg_rating == 'None' %}
              <p>No Reviews</p>
              {% endif %}
              {% if avg_rating != 'None' %}
              <p>Overall Rating: {{ avg_rating }} / 5</p>
              {% endif %}
              <p>{{ reviews.count }} Review(s)</p>
              
              <table class='table'>
                <tr>
                <th scope='col' width='15%'>Time</th>
                <th scope='col' width='15%'>Rating</th>
                <th scope='col' width='60%'>Review</th>
              </tr>
              {% for x in reviews %}
              <tr>
                <td>{{ x.date_added }}</td>
                <td>{{x.rating}} / 5 </td>
                <td>{{ x.review | linebreaks }}</td>
              </tr>
              {% endfor %}
              </table>
            </div>
          </div>
          
          
          {% if user.is_authenticated %}
          <div class="col-md-12 card mb-4  mt-3 ">
            <div class="card-body" style='width: 100%; height: 500px;'>
                {% if new_review %}
                  <div class="alert alert-success" role="alert">
                    Your comment is awaiting moderation
                  </div>
                  {% else %}
                  <h4 style="color: rgb(8, 11, 133);">Leave a Review For {{property.name}} </h4>
                  <form method="post" style="margin-top: 1.3em;">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary ">Submit</button>
                  </form>
                  {% endif %}
              {% else %}
                <div class="alert alert-success" role="alert">
                  Only logged in users can leave reviews.
                </div>
              {% endif %}
            </div>
          </div>
          
        </div>
      </div>


<script>
mapboxgl.accessToken = 'pk.eyJ1Ijoic2hpdmFtYW4iLCJhIjoiY2t2cHZjOTY2MmlodzJvbXRuOXMzMTRpNiJ9.8mKcr3_Z1IcZMKpO3VRC6A';
const map = new mapboxgl.Map({
container: 'map', // container ID
style: 'mapbox://styles/mapbox/streets-v11', // style URL
center: [-78.5, 38.04], // starting position [lng, lat]
zoom: 13 // starting zoom
});


var long ='{{ longet|safe }}';
var lat ='{{ lateral|safe }}';

var marker = new mapboxgl.Marker()              
    .setLngLat([ long, lat])
    //.setPopup(new mapboxl.Popup().setHTML("<p>{{address}}<p>"))
    .addTo(map);


</script>
   
</ul>




<div style="position: relative; bottom: 0%; width: 100%;">
  <footer class="text-center bg-light">
    <div class="text-center p-2" style="font-size: 14; background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright: Students in project b-13 in CS 3240: Advanced Software Development Techniques. 
      University of Virginia.
    </div>
  </footer>
</div>



</body>
</html>

project-b-13-main/app/templates/app/search.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}
{% load static %}
{% load socialaccount %}
<html>
    <head>
        <title>UVA Off-Grounds Housing</title>
    </head>
<body>
<!-- <h1>My Google OAuth Project </h1> -->

<nav class="navbar navbar-expand navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/app" style="color:#FF8C00">UVA Off-Grounds Housing</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/app">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:filter' %}">Filter</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:map' %}">Map</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app:about' %}">About</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
            <li class="nav-link" style="float: right;">User: {{ user.username }}</li>
            <a href="{% url 'app:logout' %}">{% load static %}<img src="{% static 'media/google-logout.png' %}" alt="home" height="50"></a>
        {% else %}
            <a href="{% provider_login_url 'google' %}">
            <img 
                src="https://onymos.com/wp-content/uploads/2020/10/google-signin-button-1024x260.png" 
                height="50"
            >
            </a>
        {% endif %}
        </div>
    </div>
</nav>
{% if searching %}
<center>  <h1 style="color: rgb(8, 11, 133);">You Searched for "{{searching}}".</h1></center>
    <br/>
    
</div>
<span class="counter pull-right"></span>
<table class="table table-striped w-auto" style="margin: auto; width: 70% !important;">

    <!--"table table-hover table-bordered results"-->
  <thead>
    <tr>
      <th class="col-md-5 col-xs-4">Name</th>
      <th class="col-md-5 col-xs-2">Housing Type</th>
      <th class="col-md-4 col-xs-2">Details</th>
      
    
  </thead>
  <tbody>
    {% for housing in housing%}
    <tr>
      
      <td>{{housing}}</td>
      {% if housing.housing_type == "Town_House" %}
      <td>Town House</td>
      {% else %}
      <td>{{housing.housing_type}}</td>
      {% endif %}
      <td><a class="btn btn-primary" style="background-color: rgb(8, 11, 133);" href="{% url 'app:property' housing.name %}" role="button">View</a></td>
      
    </tr>
    {% endfor %}
 
      
    </tr>
  </tbody>
</table>
<br/>
<br/>

{% else %}
   <center><h1 style="color: rgb(12, 3, 22);">You didn't search for anything!</h1></center>
   <center> <td><a class="btn btn-primary" style="background-color: rgb(8, 11, 133);" href="{% url 'app:index'%}" role="button">Return to Index</a></td></center>
{% endif %}
<div style="position: fixed; bottom: 0%; width: 100%;">
    <footer class="text-center bg-light">
        <div class="text-center p-2" style="font-size: 14; background-color: rgba(0, 0, 0, 0.05);">
        © 2021 Copyright: Students in project b-13 in CS 3240: Advanced Software Development Techniques. 
        University of Virginia.
        </div>
    </footer>
</div>

</body>
</html>